/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/layouts/footer.vue')['default']
    Header: typeof import('./src/components/layouts/header.vue')['default']
    Layouts: typeof import('./src/components/layouts/index.vue')['default']
    Main: typeof import('./src/components/layouts/main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/layouts/side.vue')['default']
  }
}
